# Generated by Django 3.2.8 on 2021-12-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diastolic', models.CharField(max_length=200)),
                ('systolic', models.CharField(max_length=200)),
                ('heartRate', models.CharField(max_length=200)),
                ('oxygenSaturation', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Conditions',
        ),
    ]
